// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'fasdfjlksadfjsfsdfsf',
    appId: 'fdasfhjdshfhdsaklfsdjafs',
    messagingSenderId: '103251756211',
    projectId: 'e-commerce-bbf91',
    authDomain: 'e-commerce-bbf91.firebaseapp.com',
    storageBucket: 'e-commerce-bbf91.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
   apiKey: 'fasdfjlksadfjsfsdfsf',
    appId: 'fdasfhjdshfhdsaklfsdjafs',
    messagingSenderId: '103251756211',
    projectId: 'e-commerce-bbf91',
    storageBucket: 'e-commerce-bbf91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'fasdfjlksadfjsfsdfsf',
    appId: 'fdasfhjdshfhdsaklfsdjafs',
    messagingSenderId: '103251756211',
    projectId: 'e-commerce-bbf91',
    storageBucket: 'e-commerce-bbf91.firebasestorage.app',
    iosBundleId: 'com.jeetstudio.ecommerceAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'fasdfjlksadfjsfsdfsf',
    appId: 'fdasfhjdshfhdsaklfsdjafs',
    messagingSenderId: '103251756211',
    projectId: 'e-commerce-bbf91',
    storageBucket: 'e-commerce-bbf91.firebasestorage.app',
    iosBundleId: 'com.jeetstudio.ecommerceAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'fasdfjlksadfjsfsdfsf',
    appId: 'fdasfhjdshfhdsaklfsdjafs',
    messagingSenderId: '103251756211',
    projectId: 'e-commerce-bbf91',
    authDomain: 'e-commerce-bbf91.firebaseapp.com',
    storageBucket: 'e-commerce-bbf91.firebasestorage.app',
  );
}
